"use client"
import React, { useEffect, useState } from 'react';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library'
import dynamic from 'next/dynamic'
import Image from 'next/image'
import Donde from './components/Donde';
import Hero from './components/Hero';
import Dresscode from './components/Dresscode';
import Regalo from './components/Regalo';

// Config variables
const NEXT_PUBLIC_SPREADSHEET_ID = "1AE9RRaedofgzn6ycw2mMrkZSDqe49z_LqIbGzkyvjuE"
const NEXT_PUBLIC_SHEET_ID = 0
const NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL = "weddingconfirmation@wedding-390813.iam.gserviceaccount.com"
const NEXT_GOOGLE_SERVICE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCamNvV6rf7vx4k\nVL1xXecizA10Kvk21XfKiLyxa/9nHUTTdRrvNtI50NPyPOhxgwn/g1MXHlGUkSui\nWxhZgGHJHjGMU25/TolIZWnXsr/GvRF++j0NJYwPnHF5rlCL9YnKm+0k3TmIzxeH\nszqzHs5TsWsUInmVSbbXCT8PXQlzJ+Mto2Ahwe6L33CAlquQAlhuAGZJTpZ59gYB\nbo1ff8HJMLjxrGEUV7ifLk0qWbLjOlsxTvWubYKen7yHylyZpMZ9YROl3Gm5BdKk\nV03fVK9kTjbvaTOzL5Y7qv0a+MskRiUBW0P9F38Dmkg5fIpyDTCmdcmxwDavr7ms\nZR2uYTXrAgMBAAECggEACnAxv7LWc1gHJ/rUw7fMaGwQqHxSUWJ+cR1kaDJbj1HJ\nmOF6TRaNgTvZY6y7IRbw8OCkFpaEeZyHrrGp5jkl4Rd5zvi/KDdcS5gVWmwGSNvx\nN3qb7qxPVaqBeu7LH3gXsqdujqOlQ9h/xTjTyM5Wrg33pediADN29fP43wewIKdA\n44rZRNqV4vGB3I6W3r+kVEB2+Rkgva72tkdYUL/aybYHPJkmei/P8yLCXPlV+Fqd\nXJpgG79OgDE9avKlvU9+oR3IBsCIxPvLdp9TIaUKCk/NordzSWSLEubn6D0djiVx\noScHp+rxEXpfNJ+CLn4byEqAUOPauTShZ+XNNRmMwQKBgQDT3D0N5eUTBox3UoKL\nHDMiefa1e5ySKeQsyUICbUuLmCpyvAgtOtDb9C13OLYamrCFt0JQIc6WAAOC/2JR\nuWaQgD/7Ye2cLZjsGcXOVyQtvlwFJSzWHB2KDJzIGHgWCf6Cq/2/f4A3QdK2QFk3\nBKpqn69CkvMMPWHwRTJpxH/H4QKBgQC6zm95EgsY31Id6bpfNBVhz+Q/Jb3xoxsj\n1f51EnnkwmuFLOIZ2qrH5tcYQk2+e/5somNimyz/RvpRAqVxVhOEzqZDrqOt7Ue7\npeMkpYLZgb00P2IkusaUhJBFmvHDqp+VdKAs5210DFOmoIYI2sTvMdwSaHBGrON5\npqaiY8qHSwKBgGH9M6AB/PnXxZBK8WY2HNCNaLZ3/er8xTSRwZ4tvwtJzhhTL9T7\npy6UuZKzAEc91PeD04AMouhuCTHFvUvfXLjpGK7ElInv7RMGuJ6/X1Ro/1bB4wME\n7gSz4LAL4T8QUE9QDYVNC5iDMVpqWNlBpzC5uu4n2ZKHsYzX9IFHCXMBAoGAIhLZ\nfmnuIEFLxy0E06y6Ybb72RDXTqYDo0u7ODuAhFt6JTaEn1alZAUVItWlPKN9Su9r\n1WaclIuryO8EomGi+cx/w0StkmH/fZjKj7qo3WeuzULqceynoBt1/Vw/0QLkTOyS\n8t3btxkwgOoyyJau6Tpc+/aU1C9g5qWhK2msXXUCgYEAvC4GkvrDMXokV+ykBypR\ndNahirGI8cA3KKlH3B2yeXjdHcHbPM8I+AaslPWLJHuwmpmCAsIgjfMIgJxUYH6V\nqJdIuhMCXa91ul21gX4AJF0k4FLxg0bgCSm1jCd5e01oX+xvnZpKYk8uX+Wu5xe7\ndNr1Qn/vI90XepLf14vEDjw=\n-----END PRIVATE KEY-----\n"

const SPREADSHEET_ID = NEXT_PUBLIC_SPREADSHEET_ID;
const SHEET_ID = NEXT_PUBLIC_SHEET_ID;
const GOOGLE_CLIENT_EMAIL = NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL;
const GOOGLE_SERVICE_PRIVATE_KEY = NEXT_GOOGLE_SERVICE_PRIVATE_KEY;

const ContactForm = () => {
  const [loading, setLoading] = useState(false);
  const [alert, setAlert] = useState(false);
  const [form, setForm] = useState({
    name: '',
    asistencia: '',
    restriccion: '',
    plusone: '',
    nameplusone: '',
    restriccionplusone: '',
    bus: '',
    mensaje: '',
  })
  const [asist, setAsist] = useState(false)
  const [plusone, setPlusOne] = useState(false)
  const [success, setSuccess] = useState(false)
  // To fix hydration error, we import the component dynamicly because
  // it uses logic that comes from third party library and cannot be modified.
  // Otherwise, we use useEffect. https://stackoverflow.com/questions/66374123/warning-text-content-did-not-match-server-im-out-client-im-in-div
  const Countdown = dynamic(
    () => import('./components/Countdown'),
    { ssr: false }
  )

  // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: GOOGLE_CLIENT_EMAIL,
    key: GOOGLE_SERVICE_PRIVATE_KEY,
    scopes: [
      'https://www.googleapis.com/auth/spreadsheets',
    ],
  });

  const doc = new GoogleSpreadsheet(SPREADSHEET_ID, serviceAccountAuth);

  const appendSpreadsheet = async (row) => {
    await doc.loadInfo();
    //Write data in the sheet 
    const sheet = doc.sheetsById[SHEET_ID];
    await sheet.addRow(row);
    console.log(row, 'here')
    setLoading(false)
    setSuccess(true)
  };

  const submitForm = (e) => {
    e.preventDefault();
    setLoading(true);

    if (
      form.name !== '' &&
      form.asistencia !== ''
    ) {
      const newRow = {
        Name: form.name,
        Asistencia: form.asistencia,
        Restriccion: form.restriccion,
        Acompanante: form.plusone,
        NombreAcompanante: form.nameplusone,
        RestriccionAcompanante: form.restriccionplusone,
        Bus: form.bus,
        Mensaje: form.mensaje,
        Date: new Date(),
      };
      appendSpreadsheet(newRow);
    }
  };

  useEffect(() => {
    const timeout = setTimeout(() => {
      setAlert(false);
    }, 4000);
    return () => clearTimeout(timeout);
  }, [alert]);

  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  const handleAsist = (e) => {
    setAsist(e.target.value)
  }

  const handlePlusOne = (e) => {
    setPlusOne(e.target.value)
  }

  return (
    <div className='bg-color'>
        <div className='flex justify-center items-center min-h-screen relative' id='section-intro'>
          <Hero />
        </div>
        <div className='flex flex-col justify-center item-center py-10 h-80' id="section-countdown">
          <Countdown />
          <Image alt="flower image" src="./flower.png" style={{ zIndex: 0 }} unoptimized width='100' height='70' className='mt-0 mb-0 mr-auto ml-auto py-2 brightness-[0.3]' />
        </div>
        <hr />
        <div className='flex flex-col justify-center item-center p-5 md:p-10' id="section-donde">
          <Donde />
        </div>
        <hr />
        <div className="flex flex-col justify-center items-center rsvp" id='section-rsvp'>
          <h2 className='text-2xl md:text-3xl self-center py-3 px-3 pt-10 font-semibold text-center	'>Répondez s’il vous plaît</h2>
          <p className='text-1xl md:text-2xl self-center p-3 pb-5 text-center'>Esperamos que seas parte de esta gran celebración. ¡Confirmanos tu asistencia!</p>
          <form
            className="flex flex-col space-y-3 w-4/5 mx-auto p-5 mb-10 relative"
            onSubmit={submitForm}
          >
            <label className="block">
              <span className="block font-semibold">Nombre y Apellido</span>
            </label>
            <input
              name="name"
              type="text"
              className="form-input form-field-contact"
              onChange={handleChange}
              value={form.name} 
              required/>

            <div className="block">
              <span className="block font-semibold">Confirmas asistencia?</span>
              <input
                name="asistencia"
                id='no'
                type="radio"
                className="mx-1 accent-pink-800"
                onChange={(e) => {
                  handleChange(e),
                    handleAsist(e);
                } }
                value={false}
                required />
                <label htmlFor='no'> No podré asistir</label>
              <br/>
              <input
                name="asistencia"
                id='si'
                type="radio"
                className="mx-1 accent-green-500"
                onChange={(e) => {
                  handleChange(e),
                    handleAsist(e);
                } }
                value={true}
                required />
                <label htmlFor='si'> Confirmo asistencia</label>
            </div>
            {asist === 'true' && (
              <><div>
                <span className="block font-semibold"> Tenés alguna restricción alimentaria? </span>
                <input
                  name="restriccion"
                  type="radio"
                  className="mx-1 accent-green-500"
                  onChange={handleChange}
                  value={'No'} 
                  required/>
                  <label> Puedo comer de todo </label>
                <br/>
                <input
                  name="restriccion"
                  type="radio"
                  className="mx-1 accent-green-500"
                  onChange={handleChange}
                  value={'Vegeta'} 
                  required/>
                  <label> Vegetariano </label>
                <br/>
                <input
                  name="restriccion"
                  type="radio"
                  className="mx-1 accent-green-500"
                  onChange={handleChange}
                  value={'Celiaco'} 
                  required/>
                  <label> Celíaco </label>
              </div>
              <div>
                  <span className="block font-semibold">Venis acompañado?</span>
                  <input
                    name="plusone"
                    type="radio"
                    className="mx-1 accent-pink-500"
                    onChange={(e) => {
                      handleChange(e),
                        handlePlusOne(e);
                    } }
                    value={false} 
                    required/>
                    <label> No </label>
                    <br/>
                  <input
                    name="plusone"
                    type="radio"
                    className="mx-1 accent-green-500"
                    onChange={(e) => {
                      handleChange(e),
                        handlePlusOne(e);
                    } }
                    value={true} 
                    required/>
                    <label> Si</label>
                </div>
                  {plusone === 'true' && (
                    <>
                    <div>
                    <label className="block">
                      <span className="block font-semibold">Nombre y apellido del acompañante</span>
                    </label>
                      <input
                        name="nameplusone"
                        type="text"
                        className="form-input form-field-contact"
                        onChange={handleChange}
                        value={form.nameplusone} 
                        required/>
                    </div>   
                    <div>
                      <label className="block">
                        <span className="block font-semibold">Alguna restricción alimentaria para tu acompañante?</span>
                      </label>
                      <input
                        name="restriccionplusone"
                        type="radio"
                        className="mx-1 accent-green-500"
                        onChange={handleChange}
                        value={'No'} 
                        required/>
                        <label> Puede comer de todo </label>
                        <br/>
                      <input
                        name="restriccionplusone"
                        type="radio"
                        className="mx-1 accent-green-500"
                        onChange={handleChange}
                        value={'Vegeta'} 
                        required/>
                        <label> Vegetariano </label>
                        <br/>
                      <input
                        name="restriccionplusone"
                        type="radio"
                        className="mx-1 accent-green-500"
                        onChange={handleChange}
                        value={'Celiaco'}
                        required />
                        <label> Celíaco </label>
                    </div>
                    </>
                  )}
                  <div>
                    <label className="block">
                      <span className="block font-semibold">Necesitas transporte de bus?</span>
                    </label>
                    <input
                      name="bus"
                      type="radio"
                      className="mx-1 accent-pink-500"
                      onChange={handleChange}
                      value={'No gracias'}
                      required />
                      <label> No</label>
                      <br/>
                      <input
                      name="bus"
                      type="radio"
                      className="mx-1 accent-green-500"
                      onChange={handleChange}
                      value={'Si por favor'}
                      required />
                      <label> Si </label>
                </div>
                  <label className="block">
                  <span className="block font-semibold">Te gustaría decirles algo a los novios?</span>
                </label><textarea
                  name="mensaje"
                  className="form-textarea form-field-contact resize-none"
                  rows="3"
                  placeholder="Dejanos un mensaje :)"
                  onChange={handleChange}
                  value={form.mensaje} /></>
          )}
          <button
            className="bg-cyan-700 text-white self-center px-3 py-1 shadow-md w-40 disabled:cursor-not-allowed disabled:bg-slate-500"
            type="submit"
            disabled={loading || success}
          >
            {loading ? (
              <div className="flex justify-center items-center gap-2">
                <div className="animate-spin">
                </div>
                <p>Enviando...</p>
              </div>
            ) : (
              <div className="flex justify-center items-center gap-2">
                <p>{success ? 'Gracias!' : 'Enviar'}</p>
              </div>
            )}
          </button>
          {success && (
              <div className="bg-green-100 border border-green-400 text-green-700 px-4 py-2 rounded text-center">
                <strong className="font-bold mr-1">Tu respuesta fue enviada con exito</strong>
              </div>
            )}
          </form>
        </div>
        <div className='flex flex-col justify-center item-center p-10 bg-pink-900 text-white' id="section-dress">
          <Dresscode />
        </div>
        <div className='flex flex-col justify-center item-center p-10' id="section-contribucion">
          <Regalo />
          <Image alt="flower image" src="./florecitas.jpg" style={{ zIndex: 0 }} unoptimized width='250' height='100' className='mt-0 mb-0 mr-auto ml-auto py-2' />
        </div>
        <div className='flex flex-col justify-center item-center p-10 bg-pink-900 text-white' id="section-final">
          <h2 className='text-1xl md:text-2xl self-center py-3 text-center'>¡Gracias por acompañarnos en este momento tan importante!</h2>
        </div>
    </div>
  );
};

export default ContactForm;